### ISSUE TITLE
불필요 기능 제거 및 수정

### ISSUE THREAD

**Issue by bongbongco** [bongbongco/2016-Utilizing-traffic-data-Contest#1]
졸음 운전 방지를 위한 기능 중 두 개의 기능을 제거 및 수정을 결정하였습니다. 대상이 되는 기능은 다음과 같습니다.
1. 가속도 센서를 이용한 흔들림 인식
2. 졸음을 유발하는 기온 체크 후 알림

운전자 안면인식을 이용한 졸음 인식이 신뢰성이 낮다는 판단하에 센서를 이용하여 오탐율을 낮추려고 생각하였으나 테스트 결과 높은 인식률이 확인되었으므로 해당 기능을 제외하는 것으로 판단하였습니다. 추가로 기온의 경우 차량 내부의 온도를 스마트 폰이 측정할 수 없으므로 운전자가 위치한 곳의 기온을 측정하는 것으로 계획되었습니다. 하지만 검토 결과 기능의 실효성이 낮다고 판단되어 제외를 결정하였습니다. 졸음 유발 조건 발견 시 운전자에게 알림을 주는 기능의 기획 자체는 좋아보여 기온이 아닌 다른 인자로 이를 확안하는 방안을 논의하였으면 합니다. 의견 부탁드립니다.

**Comment by rlxor1233** [comment]
졸음 운전 발생시 운전자가 가속 페달을 무의식적으로 밟는 경우 앞차와의 제동 거리가 가까워짐에 따라
사고 발생 확률이 높아진다고 생각합니다. 그래서 스마트폰 카메라의 영상 인식을 통해 앞차와의 제동 거리가 가까워지면 경고음을 알려주는 기능 추가 하는 것은 어떨지요.

**Comment by bongbongco** [comment]
전면, 후면 카메라의 동시 사용이 걱정이었는데 해당 부분이 구현 가능한 것으로 보입니다. 실제 프로젝트 시작 전 시간을 이용해서 테스트를 진행하고 문제 없을 시 추가하는 것으로 하겠습니다.
