### ISSUE TITLE
교통 데이터 활용 방안 필요

### ISSUE THREAD

**Issue by bongbongco** [bongbongco/2016-Utilizing-traffic-data-Contest#2]
교통 데이터 API를 활용한 기능 추가가 필요합니다. 현재 앱 자체 기능은 비교적 방향이 잡혀가고 있으나 교통 데이터 API의 활용 방안이 너무 미약한 상태입니다. 
1. 운전자에게 도움이 될만한 것
2. 졸음 예방에 도움이 될만한 것
3. 사고 예방에 도움이 될만한 것

위 세 가지 목표에 부합되는 API 활용 방안을 세우는 것이 필요합니다.

**Comment by rlxor1233** [comment]
회의 결과 고속도로 재난 정보 API를 활용하여 운전자에게 고속도로 사고를 사전에 알려주어 2차 사고를 방지해주는 기능을 추가하기로 결정 하였습니다.
