### ISSUE TITLE
스마트 폰 충격 감지 테스트

### ISSUE THREAD

**Issue by bongbongco** [bongbongco/2016-Utilizing-traffic-data-Contest#6]
스마트 폰의 충격 감지 테스트가 필요합니다.
테스트 마감 일을 숙지하고 진행 결과를 남겨주시기 바랍니다.

**Comment by rlxor1233** [comment]
현재 스마트폰의 가속도 센서값을 읽어들여서 출력되는 부분까지 진행되었습니다.
이 기능은 이제 충격에 따른 센서값의 변화를 테스트 한 뒤에 진행하도록 하겠습니다.

**Comment by LeeKitaek** [comment]
스마트폰의 센서값을 활용하여 충돌 감지를 한 뒤 타이머 시간 내에 음성 인식으로 사고 여부를 판단하는
기능을 구현 하였습니다. 

추가적으로 긴급 신고를 하는 구현 부분과 충돌 감지 기능의 쓰레드화를 진행하도록 하겠습니다.

**Comment by bongbongco** [comment]
충돌 감지 기능의 테스트와 메인 프로젝트에 병합 작업을 완료하였습니다.
추가적으로 실제 운전 테스트를 통한 센서 민감도 테스트가 필요할 것 같습니다.
이슈를 마감하고 새 이슈에 해당 내용을 반영하도록 하겠습니다.
