### ISSUE TITLE
사고 인식 후 긴급 신고 테스트

### ISSUE THREAD

**Issue by bongbongco** [bongbongco/2016-Utilizing-traffic-data-Contest#8]
사고 인식 후 긴급 신고를 접수하기 위한 방법의 결정이 필요합니다.
구체적인 구현 방법을 결정한 뒤 테스트 마감 일을 숙지하고 진행 결과를 남겨주시기 바랍니다.

**Comment by bongbongco** [comment]
사고가 발생하지 않은 경우, 사용자가 이를 쉽게 입력할 수 있게 음성 인식 기능의 제공이 필요합니다.
API는 구글에서 제공하는 공식 API를 사용하여 구현하도록 하며 옵션에서 설정한 긴급 연락 대기 시간 내 
정해진 단어를 인식하면 비 사고 처리 합니다.

**Comment by LeeKitaek** [comment]
충돌 감지 후 사고 유무를 판단 하기 위해 음성 인식 기능을 구현하였습니다.
사용자는 터치 없이 음성 인식 만으로 조작 할 수 있도록 구현 하였습니다.

**Comment by bongbongco** [comment]
음성인식 기능의 테스트 및 메인 프로젝트에 병합 작업을 완료하였습니다.
